apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: crud-app
type: Opaque
data:
  # postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  # postgres (base64 encoded)
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # crud_devops_db (base64 encoded)
  POSTGRES_DB: Y3J1ZF9kZXZvcHNfZGI=